# Generated by Django 2.1.5 on 2020-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='MEng',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='MS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='PhD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='title',
            field=models.CharField(default=123, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=models.TextField(default=222),
            preserve_default=False,
        ),
    ]
