# Generated by Django 2.1.5 on 2020-02-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20200212_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'title', 'verbose_name_plural': 'policy'},
        ),
    ]
