# Generated by Django 2.1.5 on 2020-02-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_auto_20200213_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'policy'},
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='title',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='description',
        ),
        migrations.AddField(
            model_name='policy',
            name='Blanket_Credits',
            field=models.CharField(default=0, max_length=120, verbose_name='Blanket Credits'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='Breadth_Requirement',
            field=models.TextField(blank=True, verbose_name='Breadth Requirement'),
        ),
        migrations.AddField(
            model_name='policy',
            name='Depth_Requirement',
            field=models.TextField(blank=True, verbose_name='Depth Requirement'),
        ),
        migrations.AddField(
            model_name='policy',
            name='EECS_Colloquium',
            field=models.TextField(blank=True, verbose_name='EECS Colloquium'),
        ),
        migrations.AddField(
            model_name='policy',
            name='Responsible_Conduct_of_Research_Training',
            field=models.TextField(blank=True, verbose_name='Responsible Conduct of Research Training'),
        ),
        migrations.AddField(
            model_name='policy',
            name='Theoretical_Computer_Science',
            field=models.CharField(default=0, max_length=120, verbose_name='Theoretical Computer Science'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='Thesis_or_Project',
            field=models.CharField(default=0, max_length=120, verbose_name='Thesis or Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='Total_Graduate_Credits',
            field=models.CharField(default=0, max_length=120, verbose_name='Total Graduate Credits'),
            preserve_default=False,
        ),
    ]
