# Generated by Django 2.1.5 on 2020-02-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20200213_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='Blanket_Credits',
            field=models.CharField(blank=True, max_length=120, verbose_name='Blanket Credits'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Theoretical_Computer_Science',
            field=models.CharField(blank=True, max_length=120, verbose_name='Theoretical Computer Science'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Thesis_or_Project',
            field=models.CharField(blank=True, max_length=120, verbose_name='Thesis or Project'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Total_Graduate_Credits',
            field=models.CharField(blank=True, max_length=120, verbose_name='Total Graduate Credits'),
        ),
    ]
