# Generated by Django 2.1.5 on 2020-02-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_auto_20200213_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'CS_policy'},
        ),
    ]
