# Generated by Django 2.1.5 on 2020-02-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_auto_20200213_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='Blanket_Credits',
            field=models.TextField(blank=True, verbose_name='Blanket Credits'),
        ),
    ]
