# Generated by Django 2.1.5 on 2020-02-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_auto_20200213_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='Thesis_or_Project',
            field=models.TextField(blank=True, verbose_name='Thesis or Project'),
        ),
    ]
