# Generated by Django 2.1.5 on 2020-02-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0010_auto_20200213_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='Category',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='policy',
            name='year_in_school',
            field=models.CharField(choices=[('M.S.', 'Freshman'), ('M.Eng.', 'Sophomore'), ('Ph.D.', 'Junior')], default='M.S.', max_length=2),
        ),
    ]
