# Generated by Django 2.1.5 on 2020-02-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_auto_20200213_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='year_in_school',
            field=models.CharField(choices=[('M.S.', 'M.S.'), ('M.Eng.', 'M.Eng.'), ('Ph.D.', 'Ph.D.')], default='M.S.', max_length=2),
        ),
    ]
