# Generated by Django 2.1.5 on 2020-02-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0012_auto_20200213_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'requirement', 'verbose_name_plural': 'CS_policy'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='year_in_school',
            field=models.CharField(choices=[('MS', 'M.S.'), ('MEng', 'M.Eng.'), ('PhD', 'Ph.D.')], default='MS', max_length=2),
        ),
    ]
