# Generated by Django 2.1.5 on 2020-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_auto_20200213_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='Program',
            field=models.CharField(choices=[('MS', 'M.S.'), ('MEng', 'M.Eng.'), ('PhD', 'Ph.D.')], default='MS', max_length=12),
        ),
    ]
