# Generated by Django 2.1.5 on 2020-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0016_auto_20200213_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='Basic_Requirement',
            field=models.TextField(blank=True, verbose_name='Basic Requirement'),
        ),
    ]
